# Dependabot to monitor package ecosystems to monitor for updates
version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[CHORE] python-deps"
    groups:
      uv-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[CHORE] python-deps"
    groups:
      gh-actions-deps:
        patterns:
          - "*"
