# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
        exclude: ^misc/
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: ^tests/test_data/sample_items.yaml
      - id: debug-statements
        exclude: syncall/pdb_cli_utils.py
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/lycheeverse/lychee.git
    rev: v0.15.1
    hooks:
      - id: lychee-docker
        # Optionally include additional CLI arguments
        # args: ["--no-progress", "--exclude", "file://"]
        types: [markdown]
  - repo: https://github.com/markdownlint/markdownlint
    rev: "v0.12.0"
    hooks:
      - id: markdownlint
        exclude: ^.github/
        entry: mdl -r ~MD033,~MD013,~MD034,~MD029,~MD007
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.37.2"
    hooks:
      - id: check-github-workflows

  - repo: local
    hooks:
      - id: just-format
        name: just format
        description: "Make sure that the justfile is formatted"
        entry: just self-fmt
        language: system
        pass_filenames: false

      - id: _check-devbox-activated
        name: check devbox is activated
        description: "Make sure that the devbox is activated before attempting to commit"
        entry: bootstrap/pre-commit/check-devbox-activated.py
        language: system
        pass_filenames: false


      - id: pyupgrade
        name: Pyupgrade
        description: Automatically upgrade syntax for newer versions.
        entry: pyupgrade
        args: ["--py38-plus"]
        types_or: [python]
        language: system

      # - id: mypy
      #   name: Mypy check
      #   entry: mypy
      #   language: system
      #   pass_filenames: true
      #   types_or: [python, pyi]
      # - id: pyright
      #   name: Pyright check
      #   entry: pyright
      #   language: system
      #   pass_filenames: true
      #   types_or: [python, pyi]
      # - id: Pylint check
      #   name: pylint
      #   entry: pylint
      #   language: system
      #   pass_filenames: true
      #   types: [python]
      #   exclude: ^tests/

      - id: ruff
        name: Ruff Linter
        entry: ruff
        args: ["check", "--fix"]
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff
        name: Ruff Format
        entry: ruff
        args: ["format", "--force-exclude"]
        language: system
        types_or: [python, pyi]
        require_serial: true

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
