#!/bin/sh
ROOT=$(realpath $(dirname $(readlink -f $0))/..)
$ROOT/scripts/check_style.py --check-only
ret=$?

if [ $ret = "0" ];
then
    echo "$(tput setaf 2)Style checks passed$(tput sgr 0)"
else
    echo "$(tput setaf 1)Style checks failed - ec: $ret\nConsider fixing them for the CI to pass.$(tput sgr 0)"
fi
