name: Style and Linters
on:
  push:
  pull_request:
jobs:
  style_and_linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Install prerequisites
        run: uv sync --all-extras --group dev
      - name: "Run pre-commit hooks"
        run: uv run pre-commit run --show-diff-on-failure --color=always --all-files
